# 389. Find the Difference
# Easy
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
#
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"
#
# Constraints:
# - 0 <= s.length <= 1000
# - t.length == s.length + 1
# - s and t consist of lowercase English letters.

def findTheDifference(s: str, t: str) -> str:
    hashMap = {}
    hashMapTwo = {}
    for index, value in enumerate(s):
        if value in hashMap:
            hashMap[value] += 1
        else:
            hashMap[value] = 1

    for index, value in enumerate(t):
        if value in hashMapTwo:
            hashMapTwo[value] += 1
        else:
            hashMapTwo[value] = 1

    for index, value in enumerate(hashMapTwo):
        if value in hashMap:
            if hashMapTwo[value] != hashMap[value]:
                return value
        elif value not in hashMap:
            return value

print(findTheDifference("abcd", "abcde"))
print(findTheDifference("", "y"))
print(findTheDifference("a", "aa"))
print(findTheDifference("abcd", "abcsd"))
print(findTheDifference("abcd", "abccd"))